const WORDS = [
  // === GREETINGS ===
  {id:"greet_01",latin:"šlomo",serto:"ܫܠܳܡܐ",en:"Hello / Peace",de:"Hallo / Friede",cat:"greetings",note:"Most common greeting. Literally 'peace'."},
  {id:"greet_02",latin:"šlomo lux",serto:"ܫܠܳܡܐ ܠܘܟ݂",en:"Peace be upon you (m.)",de:"Friede sei mit dir (m.)",cat:"greetings"},
  {id:"greet_03",latin:"šlomo lax",serto:"ܫܠܳܡܐ ܠܰܟ݂",en:"Peace be upon you (f.)",de:"Friede sei mit dir (f.)",cat:"greetings"},
  {id:"greet_04",latin:"ewa",serto:"ܐܶܘܰܐ",en:"Yes",de:"Ja",cat:"greetings"},
  {id:"greet_05",latin:"lo",serto:"ܠܐ",en:"No",de:"Nein",cat:"greetings"},
  {id:"greet_06",latin:"tawdi",serto:"ܬܰܘܕܝ",en:"Thank you",de:"Danke",cat:"greetings",note:"From Classical Syriac tawditha."},
  {id:"greet_07",latin:"b-šayno",serto:"ܒܫܰܝܢܐ",en:"Goodbye",de:"Auf Wiedersehen",cat:"greetings",note:"Literally 'in peace'."},
  {id:"greet_08",latin:"aydarbo hat?",serto:"ܐܰܝܕܰܪܒܐ ܗܰܬ",en:"How are you?",de:"Wie geht es dir?",cat:"greetings"},
  {id:"greet_09",latin:"ṭowo-no, tawdi",serto:"ܛܳܘܐ ܢܐ",en:"I'm fine, thanks",de:"Gut, danke",cat:"greetings",note:"ṭowo=good, -no=I am"},
  {id:"greet_10",latin:"mu šmux?",serto:"ܡܘ ܫܡܘܟ݂",en:"What's your name? (m.)",de:"Wie heißt du? (m.)",cat:"greetings"},
  {id:"greet_11",latin:"b sayno",serto:"ܒܫܰܝܢܐ",en:"Hello (reply)",de:"Hallo (Antwort)",cat:"greetings"},
  {id:"greet_12",latin:"esmi ... yo",serto:"ܐܶܫܡܝ ... ܝܐ",en:"My name is ...",de:"Mein Name ist ...",cat:"greetings"},
  {id:"greet_13",latin:"tawwe na",serto:"ܛܰܘܘܶܐ ܢܰ",en:"We are fine",de:"Uns geht es gut",cat:"greetings"},
  {id:"greet_14",latin:"mayko kotat?",serto:"ܡܰܝܟܐ ܟܳܐܬܰܬ",en:"Where are you from?",de:"Woher kommst du?",cat:"greetings"},
  {id:"greet_15",latin:"men kocawdat?",serto:"ܡܶܢ ܟܳܥܰܘܕܰܬ",en:"What do you do?",de:"Was arbeitest du?",cat:"greetings"},
  {id:"greet_16",latin:"malfono no",serto:"ܡܰܠܦܳܢܐ ܢܐ",en:"I am a teacher",de:"Ich bin Lehrer",cat:"greetings"},
  {id:"greet_17",latin:"fes be slomo",serto:"ܦܶܫ ܒܶ ܫܠܳܡܐ",en:"Goodbye (formal)",de:"Auf Wiedersehen",cat:"greetings"},
  {id:"greet_18",latin:"galabe tawwo",serto:"ܓܰܠܰܒܶ ܛܰܘܘܐ",en:"Very good",de:"Sehr gut",cat:"greetings"},
  {id:"greet_19",latin:"subqono",serto:"ܫܘܒܩܳܢܐ",en:"Excuse me",de:"Entschuldigung",cat:"greetings"},
  // === FAMILY ===
  {id:"fam_01",latin:"babo",serto:"ܒܰܒܐ",en:"Father",de:"Vater",cat:"family",gender:"m"},
  {id:"fam_02",latin:"emo",serto:"ܐܶܡܐ",en:"Mother",de:"Mutter",cat:"family",gender:"f",note:"Cognate: Hebrew 'em', Arabic 'umm'."},
  {id:"fam_03",latin:"abro",serto:"ܐܰܒܪܐ",en:"Son",de:"Sohn",cat:"family",gender:"m"},
  {id:"fam_04",latin:"barṯo",serto:"ܒܰܪܬ݂ܐ",en:"Daughter",de:"Tochter",cat:"family",gender:"f"},
  {id:"fam_05",latin:"aḥuno",serto:"ܐܰܚܘܢܐ",en:"Brother",de:"Bruder",cat:"family",gender:"m"},
  {id:"fam_06",latin:"ḥoṯo",serto:"ܚܳܬ݂ܐ",en:"Sister",de:"Schwester",cat:"family",gender:"f"},
  {id:"fam_07",latin:"gawro",serto:"ܓܰܘܪܐ",en:"Husband / Man",de:"Ehemann / Mann",cat:"family",gender:"m"},
  {id:"fam_08",latin:"aṯto",serto:"ܐܰܬ݂ܬܐ",en:"Wife / Woman",de:"Ehefrau / Frau",cat:"family",gender:"f"},
  {id:"fam_09",latin:"jdo",serto:"ܓܕܐ",en:"Grandfather",de:"Großvater",cat:"family",gender:"m",note:"Colloquial. Cf. formal qasso."},
  {id:"fam_10",latin:"mayme",serto:"ܡܰܝܡܶܐ",en:"Grandmother",de:"Großmutter",cat:"family",gender:"f",note:"Colloquial. Cf. formal qasto."},
  {id:"fam_11",latin:"qasso",serto:"ܩܰܫܫܐ",en:"Grandfather",de:"Großvater",cat:"family",gender:"m",note:"Formal. Cf. colloquial jdo."},
  {id:"fam_12",latin:"qasto",serto:"ܩܰܫܬ݂ܐ",en:"Grandmother",de:"Großmutter",cat:"family",gender:"f",note:"Formal. Cf. colloquial mayme."},
  {id:"fam_13",latin:"cammo",serto:"ܥܰܡܡܐ",en:"Uncle (paternal)",de:"Onkel (väterlich)",cat:"family",gender:"m"},
  {id:"fam_14",latin:"camto",serto:"ܥܰܡܬ݂ܐ",en:"Aunt (paternal)",de:"Tante (väterlich)",cat:"family",gender:"f"},
  {id:"fam_15",latin:"holo",serto:"ܚܳܠܐ",en:"Uncle (maternal)",de:"Onkel (mütterlich)",cat:"family",gender:"m"},
  {id:"fam_16",latin:"hulto",serto:"ܚܘܠܬ݂ܐ",en:"Aunt (maternal)",de:"Tante (mütterlich)",cat:"family",gender:"f"},
  {id:"fam_17",latin:"iqarto",serto:"ܐܝܩܰܪܬ݂ܐ",en:"Family (name)",de:"Familie",cat:"family",gender:"f"},
  {id:"fam_18",latin:"nacime",serto:"ܢܰܥܝܡܶ",en:"Children",de:"Kinder",cat:"family"},
  {id:"fam_19",latin:"cemro",serto:"ܥܶܡܪܐ",en:"Age",de:"Alter",cat:"family",gender:"m"},
  // === FOOD ===
  {id:"food_01",latin:"laḥmo",serto:"ܠܰܚܡܐ",en:"Bread",de:"Brot",cat:"food",gender:"m",note:"Cognate: Hebrew 'lechem'. Central to cuisine."},
  {id:"food_02",latin:"maye",serto:"ܡܰܝܶܐ",en:"Water",de:"Wasser",cat:"food",gender:"m",note:"Always plural form."},
  {id:"food_03",latin:"ḥalbo",serto:"ܚܰܠܒܐ",en:"Milk",de:"Milch",cat:"food",gender:"m"},
  {id:"food_04",latin:"čaye",serto:"ܫܰܝ",en:"Tea",de:"Tee",cat:"food",note:"Loanword via Turkish."},
  {id:"food_05",latin:"qahwe",serto:"ܩܰܗܘܶܐ",en:"Coffee",de:"Kaffee",cat:"food",note:"Arabic loanword."},
  {id:"food_06",latin:"ḥamro",serto:"ܚܰܡܪܐ",en:"Wine",de:"Wein",cat:"food",gender:"m"},
  {id:"food_07",latin:"basro",serto:"ܒܣܪܐ",en:"Meat",de:"Fleisch",cat:"food",gender:"m"},
  {id:"food_08",latin:"melḥo",serto:"ܡܶܠܚܐ",en:"Salt",de:"Salz",cat:"food",gender:"m"},
  {id:"food_09",latin:"muklo",serto:"ܡܘܟܠܐ",en:"Food / Meal",de:"Essen",cat:"food",gender:"m"},
  {id:"food_10",latin:"nunṯo",serto:"ܢܘܢܬ݂ܐ",en:"Fish",de:"Fisch",cat:"food",gender:"f"},
  // === BODY ===
  {id:"body_01",latin:"rišo",serto:"ܪܝܫܐ",en:"Head",de:"Kopf",cat:"body",gender:"m"},
  {id:"body_02",latin:"cayno",serto:"ܥܰܝܢܐ",en:"Eye",de:"Auge",cat:"body",gender:"f",note:"Also means 'spring/source'."},
  {id:"body_03",latin:"femo",serto:"ܦܶܡܐ",en:"Mouth",de:"Mund",cat:"body",gender:"m"},
  {id:"body_04",latin:"lešono",serto:"ܠܶܫܳܢܐ",en:"Tongue / Language",de:"Zunge / Sprache",cat:"body",gender:"m"},
  {id:"body_05",latin:"iḏo",serto:"ܐܝܕ݂ܐ",en:"Hand",de:"Hand",cat:"body",gender:"f"},
  {id:"body_06",latin:"lebo",serto:"ܠܶܒܐ",en:"Heart",de:"Herz",cat:"body",gender:"m",note:"Cognate: Hebrew 'lev'."},
  {id:"body_07",latin:"raġlo",serto:"ܪܰܓ݂ܠܐ",en:"Foot",de:"Fuß",cat:"body",gender:"f"},
  {id:"body_08",latin:"aḏno",serto:"ܐܰܕ݂ܢܐ",en:"Ear",de:"Ohr",cat:"body",gender:"f"},
  // === NATURE ===
  {id:"nat_01",latin:"šëmšo",serto:"ܫܶܡܫܐ",en:"Sun",de:"Sonne",cat:"nature",gender:"f"},
  {id:"nat_02",latin:"sahro",serto:"ܣܰܗܪܐ",en:"Moon",de:"Mond",cat:"nature",gender:"m"},
  {id:"nat_03",latin:"arco",serto:"ܐܰܪܥܐ",en:"Earth",de:"Erde",cat:"nature",gender:"f"},
  {id:"nat_04",latin:"šmayo",serto:"ܫܡܰܝܐ",en:"Sky / Heaven",de:"Himmel",cat:"nature",gender:"m"},
  {id:"nat_05",latin:"nuro",serto:"ܢܘܪܐ",en:"Fire",de:"Feuer",cat:"nature",gender:"f"},
  {id:"nat_06",latin:"bayto",serto:"ܒܰܝܬܐ",en:"House / Home",de:"Haus",cat:"house",gender:"m",note:"Plural: bote (irregular)."},
  {id:"nat_07",latin:"kalbo",serto:"ܟܰܠܒܐ",en:"Dog",de:"Hund",cat:"animals",gender:"m"},
  {id:"nat_08",latin:"yawmo",serto:"ܝܰܘܡܐ",en:"Day",de:"Tag",cat:"nature",gender:"m"},
  {id:"nat_09",latin:"lalyo",serto:"ܠܰܠܝܐ",en:"Night",de:"Nacht",cat:"nature",gender:"m"},
  {id:"nat_10",latin:"kṯowo",serto:"ܟܬ݂ܳܘܐ",en:"Book",de:"Buch",cat:"house",gender:"m",note:"Related to koṯaw (to write)."},
  // === NUMBERS ===
  {id:"num_01",latin:"ḥa / ḥḏo",serto:"ܚܰܐ",en:"One",de:"Eins",cat:"numbers"},
  {id:"num_02",latin:"tre / tarte",serto:"ܬܪܶܐ",en:"Two",de:"Zwei",cat:"numbers"},
  {id:"num_03",latin:"tloṯo",serto:"ܬܠܳܬ݂ܐ",en:"Three",de:"Drei",cat:"numbers"},
  {id:"num_04",latin:"arbco",serto:"ܐܰܪܒܥܐ",en:"Four",de:"Vier",cat:"numbers"},
  {id:"num_05",latin:"ḥamšo",serto:"ܚܰܡܫܐ",en:"Five",de:"Fünf",cat:"numbers"},
  // === VOCABULARY FROM BOOK ===
  {id:"alph_01",latin:"dayro",serto:"ܕܰܝܪܐ",en:"Monastery",de:"Kloster",cat:"house",gender:"m"},
  {id:"alph_02",latin:"gubo",serto:"ܓܘܒܐ",en:"Well",de:"Brunnen",cat:"nature",gender:"m"},
  {id:"alph_03",latin:"dahwo",serto:"ܕܰܗܘܐ",en:"Gold",de:"Gold",cat:"nature",gender:"m"},
  {id:"alph_04",latin:"talgo",serto:"ܬܰܠܓܐ",en:"Snow",de:"Schnee",cat:"nature",gender:"m"},
  {id:"alph_05",latin:"melto",serto:"ܡܶܠܬ݂ܐ",en:"Word",de:"Wort",cat:"house",gender:"f"},
  {id:"alph_06",latin:"canta",serto:"ܥ̰ܰܢܛܐ",en:"Bag",de:"Tasche",cat:"house",gender:"f"},
  {id:"alph_07",latin:"jazwe",serto:"ܓ̰ܰܙܘܶܐ",en:"Coffee pot",de:"Kaffeekanne",cat:"food",gender:"f"},
  {id:"alph_08",latin:"zabno",serto:"ܙܰܒܢܐ",en:"Time",de:"Zeit",cat:"nature",gender:"m"},
  {id:"alph_09",latin:"mdito",serto:"ܡܕܝܬ݂ܐ",en:"City",de:"Stadt",cat:"house",gender:"f"},
  // === GRAMMAR (Pronouns & Copula) ===
  {id:"gram_01",latin:"ono",serto:"ܐܳܢܐ",en:"I",de:"ich",cat:"grammar"},
  {id:"gram_02",latin:"hat",serto:"ܗܰܬ",en:"you",de:"du",cat:"grammar"},
  {id:"gram_03",latin:"hiye",serto:"ܗܝܝܶ",en:"he",de:"er",cat:"grammar",gender:"m"},
  {id:"gram_04",latin:"hiya",serto:"ܗܝܝܰ",en:"she",de:"sie",cat:"grammar",gender:"f"},
  {id:"gram_05",latin:"ahna",serto:"ܐܰܚܢܰ",en:"we",de:"wir",cat:"grammar"},
  {id:"gram_06",latin:"hatu",serto:"ܗܰܬ݂ܘ",en:"you (pl.)",de:"ihr",cat:"grammar"},
  {id:"gram_07",latin:"henne",serto:"ܗܶܢܢܶ",en:"they",de:"sie (Pl.)",cat:"grammar"},
  {id:"gram_08",latin:"-no",serto:"ܢܐ",en:"I am",de:"ich bin",cat:"grammar",note:"Copula 1st sg. Enclitic: malfono-no = I am a teacher."},
  {id:"gram_09",latin:"-yo",serto:"ܝܐ",en:"he/she is",de:"er/sie ist",cat:"grammar",note:"Copula 3rd sg. Enclitic: tawwo-yo = he is good."},
  {id:"gram_10",latin:"-na",serto:"ܢܰ",en:"we are",de:"wir sind",cat:"grammar",note:"Copula 1st pl. Enclitic: tawwe-na = we are good."},
];

const CATEGORIES = {
  greetings:{name:"Greetings",de:"Begrüßungen",icon:"👋",color:"#58CC02"},
  family:{name:"Family",de:"Familie",icon:"👨‍👩‍👧‍👦",color:"#E8A317"},
  food:{name:"Food & Drink",de:"Essen & Trinken",icon:"🍞",color:"#D33131"},
  body:{name:"Body",de:"Körper",icon:"🫀",color:"#8549BA"},
  nature:{name:"Nature & Time",de:"Natur & Zeit",icon:"☀️",color:"#1CB0F6"},
  house:{name:"Home",de:"Zuhause",icon:"🏠",color:"#F49000"},
  animals:{name:"Animals",de:"Tiere",icon:"🐕",color:"#89E219"},
  numbers:{name:"Numbers",de:"Zahlen",icon:"🔢",color:"#4A6FA5"},
  grammar:{name:"Grammar",de:"Grammatik",icon:"🧩",color:"#CE82FF"}
};

const PROVERBS = [
  {latin:"Man d-lo ko yolaf, lo ko yodac.",en:"He who does not learn, does not know.",de:"Wer nicht lernt, weiß nicht."},
  {latin:"U lešono tëštoco d-u calmo yo.",en:"Language is the key to the world.",de:"Die Sprache ist der Schlüssel zur Welt."},
  {latin:"Bayto d-lo kṯowe, bayto xarbo yo.",en:"A house without books is a ruined house.",de:"Ein Haus ohne Bücher ist ein zerstörtes Haus."},
];
