// ============================================================
// SURAYT ALPHABET - extracted from Slomo Surayt Ch.1-2
// ============================================================
const ALPHABET = [
  // Letters that connect in BOTH directions
  {latin:"Bb",sound:"b",serto:"ܒ",name:"Bet",group:"connect-both",
    forms:{isolated:"ܒ",initial:"ܒ",medial:"ܒ",final:"ܒ"},
    examples:[{word:"bayto",serto:"ܒܰܝܬܐ",de:"Haus"},{word:"burko",serto:"ܒܘܪܟܐ",de:"Knie"}]},
  {latin:"Gg",sound:"g",serto:"ܓ",name:"Gomal",group:"connect-both",
    forms:{isolated:"ܓ",initial:"ܓ",medial:"ܓ",final:"ܓ"},
    examples:[{word:"gubo",serto:"ܓܘܒܐ",de:"Brunnen"},{word:"gawro",serto:"ܓܰܘܪܐ",de:"Mann"}]},
  {latin:"Cc",sound:"c",serto:"ܥ",name:"Ce",group:"connect-both",
    forms:{isolated:"ܥ",initial:"ܥ",medial:"ܥ",final:"ܥ"},
    examples:[{word:"cayno",serto:"ܥܰܝܢܐ",de:"Auge"},{word:"cwodo",serto:"ܥܒܳܕܐ",de:"Arbeit"}]},
  {latin:"Ff",sound:"f",serto:"ܦ",name:"Fe",group:"connect-both",
    forms:{isolated:"ܦ",initial:"ܦ",medial:"ܦ",final:"ܦ"},
    examples:[{word:"femo",serto:"ܦܶܡܐ",de:"Mund"},{word:"fardayso",serto:"ܦܰܪܕܰܝܣܐ",de:"Paradies"}]},
  {latin:"Hh",sound:"h",serto:"ܗ",name:"He",group:"connect-both",note:"Like English h",
    forms:{isolated:"ܗ",initial:"ܗ",medial:"ܗ",final:"ܗ"},
    examples:[{word:"harke",serto:"ܗܰܪܟܶ",de:"hier"}]},
  {latin:"Ii",sound:"i",serto:"ܝ",name:"Yud",group:"connect-both",
    forms:{isolated:"ܝ",initial:"ܝ",medial:"ܝ",final:"ܝ"},
    examples:[{word:"ido",serto:"ܐܝܕ݂ܐ",de:"Hand"}]},
  {latin:"Jj",sound:"j",serto:"ܓ̰",name:"Jj",group:"connect-both",note:"New letter for Surayt",
    forms:{isolated:"ܓ̰",initial:"ܓ̰",medial:"ܓ̰",final:"ܓ̰"},
    examples:[{word:"jazwe",serto:"ܓ̰ܰܙܘܶܐ",de:"Kaffeekanne"}]},
  {latin:"Kk",sound:"k",serto:"ܟ",name:"Kof",group:"connect-both",
    forms:{isolated:"ܟ",initial:"ܟ",medial:"ܟ",final:"ܟ"},
    examples:[{word:"kalbo",serto:"ܟܰܠܒܐ",de:"Hund"},{word:"ktowo",serto:"ܟܬ݂ܳܘܐ",de:"Buch"}]},
  {latin:"Ll",sound:"l",serto:"ܠ",name:"Lomad",group:"connect-both",
    forms:{isolated:"ܠ",initial:"ܠ",medial:"ܠ",final:"ܠ"},
    examples:[{word:"lebo",serto:"ܠܶܒܐ",de:"Herz"},{word:"lalyo",serto:"ܠܰܠܝܐ",de:"Nacht"}]},
  {latin:"Mm",sound:"m",serto:"ܡ",name:"Mim",group:"connect-both",
    forms:{isolated:"ܡ",initial:"ܡ",medial:"ܡ",final:"ܡ"},
    examples:[{word:"maye",serto:"ܡܰܝܶܐ",de:"Wasser"},{word:"muklo",serto:"ܡܘܟܠܐ",de:"Essen"}]},
  {latin:"Nn",sound:"n",serto:"ܢ",name:"Nun",group:"connect-both",
    forms:{isolated:"ܢ",initial:"ܢ",medial:"ܢ",final:"ܢ"},
    examples:[{word:"nuro",serto:"ܢܘܪܐ",de:"Feuer"},{word:"nunto",serto:"ܢܘܢܬ݂ܐ",de:"Fisch"}]},
  {latin:"Pp",sound:"p",serto:"ܦ̇",name:"Pe",group:"connect-both",note:"Pe with dot above = p",
    forms:{isolated:"ܦ̇",initial:"ܦ̇",medial:"ܦ̇",final:"ܦ̇"},
    examples:[{word:"plan",serto:"ܦ̇ܠܰܢ",de:"Plan"}]},
  {latin:"Qq",sound:"q",serto:"ܩ",name:"Qof",group:"connect-both",
    forms:{isolated:"ܩ",initial:"ܩ",medial:"ܩ",final:"ܩ"},
    examples:[{word:"qahwe",serto:"ܩܰܗܘܶܐ",de:"Kaffee"}]},
  {latin:"Ss",sound:"s",serto:"ܣ",name:"Semkat",group:"connect-both",
    forms:{isolated:"ܣ",initial:"ܣ",medial:"ܣ",final:"ܣ"},
    examples:[{word:"sahro",serto:"ܣܰܗܪܐ",de:"Mond"}]},
  {latin:"Xx",sound:"x",serto:"ܟ݂",name:"Xx",group:"connect-both",
    forms:{isolated:"ܟ݂",initial:"ܟ݂",medial:"ܟ݂",final:"ܟ݂"},
    examples:[{word:"xabro",serto:"ܟ݂ܰܒܪܐ",de:"Nachricht"}]},
  {latin:"Vv",sound:"v",serto:"ܒ݂",name:"Vv",group:"connect-both",note:"Bet with dot below = v",
    forms:{isolated:"ܒ݂",initial:"ܒ݂",medial:"ܒ݂",final:"ܒ݂"},
    examples:[{word:"villa",serto:"ܒ݂ܝܠܠܐ",de:"Villa"}]},
  // Letters that connect only to the RIGHT
  {latin:"Aa",sound:"a",serto:"ܐ",name:"Olaf",group:"connect-right",note:"Silent carrier letter",
    forms:{isolated:"ܐ",initial:"ܐ",medial:"ܐ",final:"ܐ"},
    examples:[{word:"abro",serto:"ܐܰܒܪܐ",de:"Sohn"},{word:"arco",serto:"ܐܰܪܥܐ",de:"Erde"}]},
  {latin:"Dd",sound:"d",serto:"ܕ",name:"Dolad",group:"connect-right",
    forms:{isolated:"ܕ",initial:"ܕ",medial:"ܕ",final:"ܕ"},
    examples:[{word:"dayro",serto:"ܕܰܝܪܐ",de:"Kloster"},{word:"dahwo",serto:"ܕܰܗܘܐ",de:"Gold"}]},
  {latin:"Hh",sound:"h",serto:"ܚ",name:"Het",group:"connect-right",note:"Emphatic h (deep throat)",
    forms:{isolated:"ܚ",initial:"ܚ",medial:"ܚ",final:"ܚ"},
    examples:[{word:"halbo",serto:"ܚܰܠܒܐ",de:"Milch"},{word:"hamro",serto:"ܚܰܡܪܐ",de:"Wein"}]},
  {latin:"Rr",sound:"r",serto:"ܪ",name:"Ris",group:"connect-right",
    forms:{isolated:"ܪ",initial:"ܪ",medial:"ܪ",final:"ܪ"},
    examples:[{word:"riso",serto:"ܪܝܫܐ",de:"Kopf"}]},
  {latin:"Tt",sound:"t",serto:"ܬ",name:"Taw",group:"connect-right",
    forms:{isolated:"ܬ",initial:"ܬ",medial:"ܬ",final:"ܬ"},
    examples:[{word:"talgo",serto:"ܬܰܠܓܐ",de:"Schnee"},{word:"tawdi",serto:"ܬܰܘܕܝ",de:"Danke"}]},
  {latin:"Ss",sound:"s",serto:"ܨ",name:"Sode",group:"connect-right",note:"Emphatic s",
    forms:{isolated:"ܨ",initial:"ܨ",medial:"ܨ",final:"ܨ"},
    examples:[{word:"soyam",serto:"ܨܳܝܰܡ",de:"er fastet"}]},
  {latin:"Tt",sound:"t",serto:"ܛ",name:"Tet",group:"connect-right",note:"Emphatic t",
    forms:{isolated:"ܛ",initial:"ܛ",medial:"ܛ",final:"ܛ"},
    examples:[{word:"turo",serto:"ܛܘܪܐ",de:"Berg"}]},
  {latin:"Ww",sound:"w",serto:"ܘ",name:"Waw",group:"connect-right",
    forms:{isolated:"ܘ",initial:"ܘ",medial:"ܘ",final:"ܘ"},
    examples:[{word:"wardo",serto:"ܘܰܪܕܐ",de:"Rose"}]},
  {latin:"Zz",sound:"z",serto:"ܙ",name:"Zay",group:"connect-right",
    forms:{isolated:"ܙ",initial:"ܙ",medial:"ܙ",final:"ܙ"},
    examples:[{word:"zabno",serto:"ܙܰܒܢܐ",de:"Zeit"}]},
  {latin:"Ss",sound:"s",serto:"ܫ",name:"Sin",group:"connect-both",
    forms:{isolated:"ܫ",initial:"ܫ",medial:"ܫ",final:"ܫ"},
    examples:[{word:"slomo",serto:"ܫܠܳܡܐ",de:"Hallo/Friede"},{word:"semso",serto:"ܫܶܡܫܐ",de:"Sonne"}]},
];

// ============================================================
// VOCABULARY BY LESSON - from Slomo Surayt
// ============================================================
const VOCAB = {
  // Lesson 1: Alphabet words
  alphabet: [
    {latin:"bayto",serto:"ܒܰܝܬܐ",de:"Haus",en:"house"},
    {latin:"dayro",serto:"ܕܰܝܪܐ",de:"Kloster",en:"monastery"},
    {latin:"femo",serto:"ܦܶܡܐ",de:"Mund",en:"mouth"},
    {latin:"gubo",serto:"ܓܘܒܐ",de:"Brunnen",en:"well"},
    {latin:"dahwo",serto:"ܕܰܗܘܐ",de:"Gold",en:"gold"},
    {latin:"ktowo",serto:"ܟܬ݂ܳܘܐ",de:"Buch",en:"book"},
    {latin:"talgo",serto:"ܬܰܠܓܐ",de:"Schnee",en:"snow"},
    {latin:"melto",serto:"ܡܶܠܬ݂ܐ",de:"Wort",en:"word"},
    {latin:"villa",serto:"ܒ݂ܝܠܠܐ",de:"Villa",en:"villa"},
    {latin:"canta",serto:"ܥ̰ܰܢܛܐ",de:"Tasche",en:"bag"},
    {latin:"jazwe",serto:"ܓ̰ܰܙܘܶܐ",de:"Kaffeekanne",en:"coffee pot"},
    {latin:"zabno",serto:"ܙܰܒܢܐ",de:"Zeit",en:"time"},
    {latin:"plan",serto:"ܦ̇ܠܰܢ",de:"Plan",en:"plan"},
    {latin:"mdito",serto:"ܡܕܝܬ݂ܐ",de:"Stadt",en:"city"},
  ],
  // Lesson 3: Greetings
  greetings: [
    {latin:"slomo",serto:"ܫܠܳܡܐ",de:"Hallo (Begruessung)",en:"hello"},
    {latin:"b sayno",serto:"ܒܫܰܝܢܐ",de:"Hallo (Antwort)",en:"hello (reply)"},
    {latin:"esmi ... yo",serto:"ܐܶܫܡܝ ... ܝܐ",de:"Mein Name ist ...",en:"my name is ..."},
    {latin:"aydarbo hat?",serto:"ܐܰܝܕܰܪܒܐ ܗܰܬ",de:"Wie geht es dir?",en:"how are you?"},
    {latin:"tawdi",serto:"ܬܰܘܕܝ",de:"Danke",en:"thanks"},
    {latin:"tawwe na",serto:"ܛܰܘܘܶܐ ܢܰ",de:"Uns geht es gut",en:"we are fine"},
    {latin:"tawwo yo",serto:"ܛܰܘܘܐ ܝܐ",de:"Mir (m.) geht es gut",en:"I'm fine (m.)"},
    {latin:"mayko kotat?",serto:"ܡܰܝܟܐ ܟܳܐܬܰܬ",de:"Woher kommst du?",en:"where are you from?"},
    {latin:"koteno mu bayto",serto:"ܟܳܐܬܶܢܐ ܡܘ ܒܰܝܬܐ",de:"Ich komme von zu Hause",en:"I come from home"},
    {latin:"men kocawdat?",serto:"ܡܶܢ ܟܳܥܰܘܕܰܬ",de:"Was arbeitest du?",en:"what do you do?"},
    {latin:"malfono no",serto:"ܡܰܠܦܳܢܐ ܢܐ",de:"Ich bin Lehrer",en:"I am a teacher"},
    {latin:"fes be slomo",serto:"ܦܶܫ ܒܶ ܫܠܳܡܐ",de:"Auf Wiedersehen",en:"goodbye"},
    {latin:"galabe tawwo",serto:"ܓܰܠܰܒܶ ܛܰܘܘܐ",de:"Sehr gut",en:"very good"},
    {latin:"subqono",serto:"ܫܘܒܩܳܢܐ",de:"Entschuldigung",en:"excuse me"},
  ],
  // Lesson 4: Family
  family: [
    {latin:"babo",serto:"ܒܰܒܐ",de:"Vater",en:"father",gender:"m"},
    {latin:"emo",serto:"ܐܶܡܐ",de:"Mutter",en:"mother",gender:"f"},
    {latin:"abro",serto:"ܐܰܒܪܐ",de:"Sohn",en:"son",gender:"m"},
    {latin:"barto",serto:"ܒܰܪܬ݂ܐ",de:"Tochter",en:"daughter",gender:"f"},
    {latin:"ahuno",serto:"ܐܰܚܘܢܐ",de:"Bruder",en:"brother",gender:"m"},
    {latin:"hoto",serto:"ܚܳܬ݂ܐ",de:"Schwester",en:"sister",gender:"f"},
    {latin:"gawro",serto:"ܓܰܘܪܐ",de:"Ehemann",en:"husband",gender:"m"},
    {latin:"atto",serto:"ܐܰܬ݂ܬ݂ܐ",de:"Ehefrau",en:"wife",gender:"f"},
    {latin:"qasso",serto:"ܩܰܫܫܐ",de:"Grossvater",en:"grandfather",gender:"m"},
    {latin:"qasto",serto:"ܩܰܫܬ݂ܐ",de:"Grossmutter",en:"grandmother",gender:"f"},
    {latin:"cammo",serto:"ܥܰܡܡܐ",de:"Onkel (vaeterlich)",en:"uncle (paternal)",gender:"m"},
    {latin:"camto",serto:"ܥܰܡܬ݂ܐ",de:"Tante (vaeterlich)",en:"aunt (paternal)",gender:"f"},
    {latin:"holo",serto:"ܚܳܠܐ",de:"Onkel (muetterlich)",en:"uncle (maternal)",gender:"m"},
    {latin:"hulto",serto:"ܚܘܠܬ݂ܐ",de:"Tante (muetterlich)",en:"aunt (maternal)",gender:"f"},
    {latin:"iqarto",serto:"ܐܝܩܰܪܬ݂ܐ",de:"Familie",en:"family"},
    {latin:"nacime",serto:"ܢܰܥܝܡܶ",de:"Kinder",en:"children"},
    {latin:"esne",serto:"ܐܶܫܢܐ",de:"Jahre",en:"years"},
    {latin:"cemro",serto:"ܥܶܡܪܐ",de:"Alter",en:"age"},
  ],
  // Grammar: Pronouns & Copula (Ch.3-4)
  grammar: [
    {latin:"ono",serto:"ܐܳܢܐ",de:"ich",en:"I"},
    {latin:"hat",serto:"ܗܰܬ",de:"du",en:"you"},
    {latin:"hiye",serto:"ܗܝܝܶ",de:"er",en:"he"},
    {latin:"hiya",serto:"ܗܝܝܰ",de:"sie",en:"she"},
    {latin:"ahna",serto:"ܐܰܚܢܰ",de:"wir",en:"we"},
    {latin:"hatu",serto:"ܗܰܬ݂ܘ",de:"ihr",en:"you (pl.)"},
    {latin:"henne",serto:"ܗܶܢܢܶ",de:"sie (Pl.)",en:"they"},
    {latin:"no",serto:"ܢܐ",de:"ich bin",en:"I am",note:"Kopula 1.Sg."},
    {latin:"yo",serto:"ܝܐ",de:"er/sie ist",en:"he/she is",note:"Kopula 3.Sg."},
    {latin:"na",serto:"ܢܰ",de:"wir sind",en:"we are",note:"Kopula 1.Pl."},
  ],
};

// ============================================================
// DIALOGUE DATA - from Slomo Surayt Ch.3
// ============================================================
const DIALOGUES = [
  {
    title:"Slomo - Meeting someone",
    context:"Afrem goes shopping and meets Saro and Aday.",
    lines:[
      {speaker:"Afrem",surayt:"Slomo, ono esmi Afrem yo.",de:"Hallo, ich heisse Afrem."},
      {speaker:"Aday",surayt:"B sayno, ono esmi Aday yo. Hate i Saro yo, i attaydi.",de:"Hallo, mein Name ist Aday. Das ist Saro, meine Frau."},
      {speaker:"Afrem",surayt:"Aydarbo hatu? U Gabriyel aydarbo yo?",de:"Wie geht es euch? Wie geht es Gabriyel?"},
      {speaker:"Saro",surayt:"Tawdi, tawwe na. U Gabriyel ste tawwo yo.",de:"Danke, uns geht es gut. Gabriyel geht es auch gut."},
      {speaker:"Afrem",surayt:"Men kosaymitu harke?",de:"Was macht ihr hier?"},
      {speaker:"Saro",surayt:"Aser kokurxina bi suqo.",de:"Nun, wir sind einkaufen."},
      {speaker:"Afrem",surayt:"Men kocawdat?",de:"Was arbeitest du?"},
      {speaker:"Aday",surayt:"Kocowadno xud malfono.",de:"Ich arbeite als Lehrer."},
      {speaker:"Afrem",surayt:"Men komelfat?",de:"Was unterrichtest du?"},
      {speaker:"Aday",surayt:"Komolafno Surayt.",de:"Ich unterrichte Surayt."},
      {speaker:"Afrem",surayt:"Galabe tawwo.",de:"Sehr gut."},
    ]
  },
  {
    title:"Iqarto - Family chat",
    context:"Maryam and Tuma talk about family.",
    lines:[
      {speaker:"Tuma",surayt:"Men yo esma di iqartatxu?",de:"Wie lautet der Name eurer Familie?"},
      {speaker:"Maryam",surayt:"Iqarto d Be Brahem.",de:"Familie Be Brahem."},
      {speaker:"Tuma",surayt:"Men yo esme d babax?",de:"Wie lautet der Name deines Vaters?"},
      {speaker:"Maryam",surayt:"Esme Aday yo.",de:"Sein Name ist Aday."},
      {speaker:"Tuma",surayt:"Kmo ahunone w hotote ketlax?",de:"Wie viele Brueder und Schwestern hast du?"},
      {speaker:"Maryam",surayt:"Ketli ha ahuno w tarte hotote.",de:"Ich habe einen Bruder und zwei Schwestern."},
      {speaker:"Tuma",surayt:"Mayko kotitu bu serso?",de:"Woher kommt ihr urspruenglich?"},
      {speaker:"Maryam",surayt:"Kotina me Turcabdin.",de:"Wir kommen aus dem Turabdin."},
    ]
  }
];

// ============================================================
// SESSION TEMPLATES
// ============================================================
const SESSIONS = [
  {id:"script",name:"Script Explorer",icon:"ܐ",desc:"Learn the Serto alphabet interactively",
    color:"#4A6FA5",type:"explorer"},
  {id:"greet",name:"First Words",icon:"👋",desc:"Greetings, hello, goodbye, thank you",
    color:"#58CC02",type:"exercises",vocab:"greetings",level:1},
  {id:"family",name:"Family Tree",icon:"👨‍👩‍👧‍👦",desc:"Mother, father, sister, brother...",
    color:"#E8A317",type:"exercises",vocab:"family",level:2},
  {id:"dialogue",name:"Role Play",icon:"💬",desc:"Practice real conversations from the book",
    color:"#8549BA",type:"exercises",vocab:"greetings",level:3},
  {id:"grammar",name:"I am, you are...",icon:"🧩",desc:"Pronouns and the copula (to be)",
    color:"#1CB0F6",type:"exercises",vocab:"grammar",level:2},
];
